services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
  postgres:
    env_file:
      - .env
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
