[DEVELOPMENT]
LOG_LEVEL = 'DEBUG'
HOST = 'localhost'
PORT = 8000

[DEVELOPMENT.AUTH]
ALGORITHM = 'HS256'
ACCESS_TOKEN_EXPIRE_MINUTES = 30


[PRODUCTION]
LOG_LEVEL = 'INFO'
HOST = '0.0.0.0'
PORT = 8000
SSL_CERTFILE = 'cert.pem'
SSL_KEYFILE = 'key.pem'

[PRODUCTION.AUTH]
ALGORITHM = 'HS256'
ACCESS_TOKEN_EXPIRE_MINUTES = 1200